# fly.toml app configuration file generated for back-rough-violet-8806 on 2024-07-27T14:21:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'back-rough-violet-8806'
primary_region = 'cdg'

[mounts]
source = "pb_data"
destination = "/pb_data"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
